{
  "language": "ruby",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "after_failure": [
    "cat config.log"
  ],
  "after_success": [
    "echo \"All tests passed!\""
  ],
  "jobs": {
    "include": [
      {
        "language": "python",
        "python": "3.7",
        "install": [
          "pip install --upgrade pip",
          "pip install ."
        ],
        "script": [
          "pytest -s"
        ]
      }
    ]
  }
}