lithic:
  threshold: 0.01
  contour_parameter: 0.1
  contour_fully_connected: 'low'
  minimum_pixels_contour: 300


scale:
  threshold: 1.0
  contour_parameter: 0.50
  contour_fully_connected: 'high'
  minimum_pixels_contour: 10
