lithic:
  threshold: 0.95
  contour_parameter: 0.4
  contour_fully_connected: 'high'
  minimum_pixels_contour: 500


scale:
  threshold: 1.0
  contour_parameter: 0.50
  contour_fully_connected: 'high'
  minimum_pixels_contour: 10
